version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bookstore_db
    restart: always
    environment:
      MYSQL_DATABASE: 'bookstore'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql  # Persistent data storage

volumes:
  mysql_data:
    driver: local
